import typography from "./typography";
import animations from "./animations";

const light = {
  typography,
  animations,
  colors: {
    primary: "#000000",
    accent: "#ED202E",
    background: "#FFFFFF",
    backgroundPrimary: "#FFFFFF",
    backgroundSecondary: "#F6F6F6",
    backgroundInversePrimary: "#000000",
    backgroundTertiary: "#EEEEEE",
    contentPrimary: "#000000",
    contentSecondary: "#545454",
    negative: "#D44333",
    warning: "#FFC043",
    positive: "#3AA76D",
    foreground: "#000000",
    foregroundAlt: "#545454",
    border: "#CBCBCB",
    borderFocus: "#000000",
    buttonPrimaryFill: "#ED202E",
    buttonPrimarySelectedFill: "#545454",
    buttonPrimaryText: "#FFFFFF",
    buttonPrimarySelectedText: "#FFFFFF",
    buttonSecondaryFill: "#EEEEEE",
    buttonSecondarySelectedFill: "#E2E2E2",
    buttonSecondaryText: "#000000",
    buttonSecondarySelectedText: "#000000",
    buttonDisabledFill: "#F6F6F6",
    buttonDisabledText: "#AFAFAF",
    inputFill: "#EEEEEE",
    inputFillDisabled: "#F6F6F6",
    inputTextDisabled: "#AFAFAF",
    inputFillError: "#FDF0EF",
    inputBorderError: "#F4AFA7",
    inputFillPositive: "#F0F9F4",
    inputBorderPositive: "#AEDDC2",
    inputFillActive: "#F6F6F6",
    notificationInfoBackground: "#EEF3FE",
    notificationInfoText: "#1E54B7",
    notificationPositiveBackground: "#F0F9F4",
    notificationPositiveText: "#368759",
    notificationWarningBackground: "#FEF3EF",
    notificationWarningText: "#B45427",
    notificationNegativeBackground: "#FDF0EF",
    notificationNegativeText: "#AE372A",
    spinnerTrackFill: "#333333",
  },
};
const dark = {
  typography,
  animations,
  colors: {
    primary: "#FFFFFF",
    accent: "#ED202E",
    background: "#000000",
    backgroundPrimary: "#141414",
    backgroundSecondary: "#1F1F1F",
    backgroundInversePrimary: "#E2E2E2",
    backgroundTertiary: "#333333",
    contentPrimary: "#E2E2E2",
    contentSecondary: "#AFAFAF",
    negative: "#D44333",
    warning: "#C19132",
    positive: "#3AA76D",
    foreground: "#CBCBCB",
    foregroundAlt: "#757575",
    border: "#292929",
    borderFocus: "#FFFFFF",
    buttonPrimaryFill: "#ED202E",
    buttonPrimarySelectedFill: "#E2E2E2",
    buttonPrimaryText: "#FFFFFF",
    buttonPrimarySelectedText: "#000000",
    buttonSecondaryFill: "#333333",
    buttonSecondarySelectedFill: "#757575",
    buttonSecondaryText: "#FFFFFF",
    buttonSecondarySelectedText: "#FFFFFF",
    buttonDisabledFill: "#292929",
    buttonDisabledText: "#757575",
    inputFill: "#292929",
    inputFillDisabled: "#141414",
    inputTextDisabled: "#333333",
    inputFillError: "#5C1D16",
    inputBorderError: "#F4AFA7",
    inputFillPositive: "#1C472F",
    inputBorderPositive: "#3AA76D",
    inputFillActive: "#333333",
    notificationInfoBackground: "#102C60",
    notificationInfoText: "#A0BFF9",
    notificationPositiveBackground: "#1C472F",
    notificationPositiveText: "#AEDDC2",
    notificationWarningBackground: "#5F2C14",
    notificationWarningText: "#F7BFA5",
    notificationNegativeBackground: "#5C1D16",
    notificationNegativeText: "#F4AFA7",
    spinnerTrackFill: "#CBCBCB",
  },
};

export { light, dark };

export default {
  light,
  dark,
};
